### ISSUE TITLE
TASK: Scope Plane

### ISSUE THREAD

**Issue by GeorginaCarlisle** [EddieStn/movember#45]
## Acceptance Criteria

1. Possible features identified
2. Features clearly communication in the form of user stories
3. Features all labelled clearly to identify priority for inclusion

## Tasks

- [ ] List Epics
- [ ] Breakdown epics into clear user stories
- [ ] Create an issue for each user story on GitHub
- [ ] Rank user stories by account importance, desirability and achievability
- [ ] Label user stories using MoSCow
