### ISSUE TITLE
DOCS: Add planning to the readme

### ISSUE THREAD

**Issue by GeorginaCarlisle** [EddieStn/movember#53]
## Acceptance Criteria

1. Readme contains clear and detailed information on all the design planning

## Tasks

- [ ] Strategy plane documented
- [ ] Scope plane documented
- [ ] Structure plane documented
- [ ] Skeleton plane documented
- [ ] Surface plane documented

**Comment by GeorginaCarlisle** [comment]
Covered by other issues
