### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by GeorginaCarlisle** [EddieStn/movember#6]
As a **registered user** I can **use my username and password to login to my account** so that **my account remains secure and only I can login**.

## Acceptance Criteria

1. Acceptance Criteria

## Tasks

- [x] Extend base.html
- [x] Add styling akin to login.html
- [ ] Check responsivity and add adjustments

**Comment by GeorginaCarlisle** [comment]
Responsive styling needed for smaller screens
